name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            pyproject.toml

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Editable install + dev extras (from your pyproject)
          pip install -e .[dev]
          # Belt-and-suspenders in case extras are missing
          pip install jinja2 jsonschema

      - name: Debug env
        run: |
          python -V
          pip --version
          pip list

      - name: Generate demo outputs (all formats)
        run: |
          python scripts/demo.py --topic "" --limit 3 --format all --outdir scripts/out/ci

      - name: Validate JSON manifests
        run: |
          python scripts/validate_manifest.py

      - name: Build feeds (local base)
        run: |
          python scripts/build_feeds.py --base-url "http://localhost:8000" --public-dir public

      - name: Build Pages index
        run: |
          python scripts/build_pages_index.py

      - name: Upload public/ as artifact (sanity)
        uses: actions/upload-artifact@v4
        with:
          name: public-ci
          path: public
