name: nightly-demo

on:
  schedule:
    # 06:30 America/New_York ≈ 10:30 UTC (adjust as you like)
    - cron: '30 10 * * *'
  workflow_dispatch:
    inputs:
      topic:
        description: 'Topic keyword (e.g., tech, climate). Leave blank to skip manual run.'
        required: false
        default: ''
      limit:
        description: 'Max stories'
        required: false
        default: '3'
      format:
        description: 'Output format (html, txt, json, cards, both, all)'
        required: false
        default: 'all'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            pyproject.toml

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
          pip install jinja2 jsonschema

      - name: Debug env
        run: |
          python -V
          pip list

      # Scheduled demo runs
      - name: Run demo (tech, limit 3)
        if: github.event_name == 'schedule'
        run: |
          python scripts/demo.py --topic tech --limit 3 --format all --outdir scripts/out/tech

      - name: Run demo (climate, limit 3)
        if: github.event_name == 'schedule'
        run: |
          python scripts/demo.py --topic climate --limit 3 --format all --outdir scripts/out/climate

      # Manual ad-hoc run
      - name: Run demo (manual, inputs)
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.topic != ''
        run: |
          TOPIC="${{ github.event.inputs.topic }}"
          LIMIT="${{ github.event.inputs.limit }}"
          FORMAT="${{ github.event.inputs.format }}"
          python scripts/demo.py --topic "$TOPIC" --limit "$LIMIT" --format "$FORMAT" --outdir scripts/out/manual

      - name: Validate manifests
        run: |
          python scripts/validate_manifest.py

      - name: Build feeds
        run: |
          OWNER="${GITHUB_REPOSITORY%/*}"
          REPO="${GITHUB_REPOSITORY#*/}"
          BASE_URL="https://${OWNER}.github.io/${REPO}"
          python scripts/build_feeds.py --base-url "$BASE_URL" --public-dir public

      - name: Build Pages index
        run: |
          python scripts/build_pages_index.py

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    environment:
      name: demo
      url: ${{ steps.deployment.outputs.page_url }}
    needs: demo
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Post URL to summary
        run: |
          echo "### GitHub Pages URL" >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.deployment.outputs.page_url }}" >> $GITHUB_STEP_SUMMARY
